version: 1.0.{build}
environment:
    COVERALLS_REPO_TOKEN:  
       secure: GWKbqcNRvtT8lNKzzlAhaUPcGtmoq1qbX8FKIAPfLQElR/l4mwu3IHTxAji2dEuE
branches:
  only:
  - master
before_build:
- cmd: nuget restore TSQL_Parser/TSQL_Parser.sln
build:
  project: TSQL_Parser/TSQL_Parser.sln
  verbosity: minimal
after_test: 
- cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[TSQL*]*" -target:"packages\\NUnit.ConsoleRunner.3.8.0\\tools\\nunit3-console.exe" -targetargs:"Tests\\bin\\Debug\\Tests.dll" -excludebyattribute:"System.CodeDom.Compiler.GeneratedCodeAttribute" -output:"Tests\\bin\\Debug\\CodeCoverageResult.xml"

- cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover Tests\bin\Debug\CodeCoverageResult.xml -r %COVERALLS_REPO_TOKEN%
